spring:
  application:
    name: msrecherche
  cloud:
    config:
      uri: http://localhost:8888

resource-base-url: http://localhost:8020

concentrateur:
  url:
    base: http://localhost:8020
    bar: ${concentrateur.url.base}/etablissement
    cocktail: ${concentrateur.url.base}/cocktail
